language: go
go:
- '1.0'
before_install:
- openssl aes-256-cbc -K $encrypted_9828b90b0055_key -iv $encrypted_9828b90b0055_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 119.29.240.215\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh ubuntu@119.29.240.215 'cd /mnt/www/server-api-doc && git pull origin master'
