FORMAT: 1A
HOST: http://api.smartwork.mobi/

# SMARTWORK API DOCUMENTS [Version 1.0]

**开发环境**

```
http://api.smartwork.mobi
```

**线上环境**

```
http://api.smartwork.mobi
```

接口签名规则：

```
```

<!-- include(./user/user.apib) -->
