# Group 任务管理

# 任务 [/task]

## 创建任务 [POST /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + temp_id: `1j2joawjj9203=`(string, required) - 任务临时ID 由客户端产生唯一uuid
    + content: `完成xxx的调研`(string, required) - 任务内容
    + estimated_stime: `2017-07-10 12:00` (string, required) - 预估开始时间 默认：当前时间
    + estimated_do: `2` (number, required) - 预估今日消耗时长 单位：h 默认：2
    + estimated_total: `8` (number, required) - 预估总时长 单位：h 默认：8->1个工作日
    + reminder: `15` (number, required) - 提醒（-1，0，10，30，60）单位：m 默认：-1->不提醒
    + priority: `false` (boolean, required) - 优先级 默认：false
    + target: `5.0版本开发`(string, optional) - 任务目标
    + desc: `xxx功能包括：1.xxx 2.xxx`(string, optional) - 任务描述

+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常
        + task_id:`201301` (number) - 任务ID

## 更新任务 [PUT /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + content: `完成xxx的调研`(string, required) - 任务内容
    + estimated_stime: `2017-07-10 12:00` (string, required) - 预估开始时间 默认：当前时间
    + estimated_do: `2` (number, required) - 预估今日消耗时长 单位：h 默认：2
    + estimated_total: `8` (number, required) - 预估总时长 单位：h 默认：8->1个工作日
    + reminder: `15` (number, required) - 提醒（-1，0，10，30，60）单位：m 默认：-1->不提醒
    + priority: `false` (boolean, required) - 优先级 默认：false
    + target: `5.0版本开发`(string, optional) - 任务目标
    + desc: `xxx功能包括：1.xxx 2.xxx`(string, optional) - 任务描述

+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常

## 删除任务 [DELETE /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + task_id: `1j2joawjj9203=`(string, required) - 任务ID
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常

## 完成任务 [PUT /task/complete]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + task_id: `1j2joawjj9203=`(string, required) - 任务ID
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常

# 子任务 [/subtask]

## 创建子任务 [POST /subtask]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + task_id: `201301` (number, required) - 父任务ID 或者 父任务临时ID
    + content: `第一步完成xxx的调研`(string, required) - 子任务内容

+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常
        + subtask_id:`28` (number) - 子任务ID

## 删除子任务 [DELETE /subtask]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + task_id: `1j2joawjj9203=`(string, required) - 任务ID
    + subtask_id: `23`(string, required) - 子任务ID
    
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应正常