# Group 任务管理

# 任务 [/task]

## 创建任务 [POST /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + content: `完成xxx的调研`(string, required) - 任务内容
    + plan_time: `1505632197` (number, required) - 预估开计划开始时间 单位：秒级时间戳
    + clock: `close` (enum) - 闹钟状态 open:设置 close:不设置 默认:close
    + clock_time: `1506223769` (number) - 闹钟时间 单位:秒级时间戳

+ Response 200 (application/json)
    + Attributes
        + chief_task_id:`201301` (number) - 任务ID

## 更新任务 [PUT /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + chief_task_id: `1212`(number , required) - 主任务ID
    + content: `完成xxx的调研`(string) - 任务内容
    + plan_time: `1505632197` (number) - 预估开计划开始时间 单位：秒级时间戳
    + clock: `open` (enum) - 闹钟状态 open:设置 close:不设置 默认:close
    + clock_time: `1505632197` (number) - 闹钟时间 单位:秒级时间戳
    + target: `5.0版本开发`(string) - 任务目标
    + desc: `xxx功能包括：1.xxx 2.xxx`(string) - 任务描述
    + level: `0` (number) - 优先级 默认:0 优先级正向递增
    + reach_goal: `yes` (enum) - 是否达成目标 yes:达成 no:未达成 默认:no
    + status: `0` (enum) - 任务状态(-1：删除; 0:开启; 1:完成; 2:重新开启)

+ Response 200 (application/json)
    + Attributes
        + affect_row_num:`1` (number) - 影响行数

## 获取用户任务列表 [GET /task/chief/:s_token?type=today]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + type: `today`(enum, required) - 任务列表类型(today:今天 future_seven:未来七天 history:历史 overdue:过期的)
    + page_num: `1`(number) - 页码(默认第一页）
    + page_size: `10`(number) - 没页数量(默认10）

+ Response 200 (application/json)
    + Body
        
        {
            "sum":10,
            "list": [
                {
                    "chief_task_id":666,
                    "content":"这是我的任务内容",
                    "plan_date_at":1505632197,
                    "clock":"open",
                    "clock_time":1505639876,
                    "sub_task_total": 5,
                    "sub_task_complete": 2,
                    "level":"0",
                    "status":"0"
                }
            ]
        }

    + Schema

        {
            "type": "json",
            "properties": {
                "sum": {
                    "type": "int"
                    "description": "列表未完成任务总数"
                },
                "chief_task_id": {
                    "type": "int"
                    "description": "主任务id"
                },
                "content": {
                    "type": "string"
                    "description": "任务内容"
                },
                "plan_date_at": {
                    "type": "int"
                    "description": "任务计划开始具体时间戳"
                },
                "clock": {
                    "type": "string"
                    "description": "闹钟状态 open:设置 close:不设置 默认:close"
                },
                "clock_time": {
                    "type": "int"
                    "description": "闹钟时间 单位:秒级时间戳"
                },
                "sub_task_total": {
                    "type": "int"
                    "description": "子任务总数"
                },
                "sub_task_complete": {
                    "type": "int"
                    "description": "未完成子任务数"
                },
                "level": {
                    "type": "int"
                    "description": "优先级 默认:0 优先级正向递增"
                },
                "status": {
                    "type": "int"
                    "description": "任务状态(-1：删除; 0:开启; 1:完成;)"
                },
            }
        }

## 获取用户任务详情 [GET /task/chief/item/:s_token?type=today]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + chief_task_id: `1232`(number, required) - 主任务ID

+ Response 200 (application/json)
    + Body
        
        {
            "chief_task_id":666,
            "content":"这是我的任务内容",
            "plan_date_at":1505632197,
            "clock":"open",
            "clock_time":1505639876,
            "level":"0",
            "status":"0",
            "sub_task_list": [
                {
                    "sub_task_id": 2112,
                    "content":"这是我的子任务内容",
                    "plan_date_at":1505632197,
                    "clock":"open",
                    "clock_time":1505639876,
                }
            ]
        }

    + Schema

        {
            "type": "json",
            "properties": {
                "chief_task_id": {
                    "type": "int"
                    "description": "主任务id"
                },
                "content": {
                    "type": "string"
                    "description": "任务内容"
                },
                "plan_date_at": {
                    "type": "int"
                    "description": "任务计划开始具体时间戳"
                },
                "clock": {
                    "type": "string"
                    "description": "闹钟状态 open:设置 close:不设置 默认:close"
                },
                "clock_time": {
                    "type": "int"
                    "description": "闹钟时间 单位:秒级时间戳"
                },
                "level": {
                    "type": "int"
                    "description": "优先级 默认:0 优先级正向递增"
                },
                "status": {
                    "type": "int"
                    "description": "任务状态(-1：删除; 0:开启; 1:完成;)"
                },
                "sub_task_id": {
                    "type": "int"
                    "description": "子任务id"
                },
            }
        }

## 删除任务 [DELETE /task]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + chief_task_id: `1001`(number, required) - 任务ID
+ Response 200 (application/json)
    + Attributes
        + affect_row_num:`1` (number) - 删除行数

# 子任务 [/subtask]

## 创建子任务 [POST /task/sub]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + chief_task_id: `201301` (number, required) - 父任务ID
    + content: `第一步完成xxx的调研`(string, required) - 子任务内容
    + plan_time: `1505632197` (number, required) - 预估开计划开始时间 单位：秒级时间戳
    + clock: `open` (enum) - 闹钟状态 open:设置 close:不设置 默认:close
    + clock_time: `1506223769` (number) - 闹钟时间 单位:秒级时间戳

+ Response 200 (application/json)
    + Attributes
        + sub_task_id:`28` (number) - 子任务ID

## 删除子任务 [DELETE /task/sub]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + chief_task_id: `222`(string, required) - 任务ID
    + sub_task_id: `23`(string, required) - 子任务ID
    
+ Response 200 (application/json)
    + Attributes
        + sub_task_id:`28` (number) - 子任务IDc
