# Group 行为管理
# 状态 [/behavior]

## 激活 [POST /behavior/active]
+ Parameters
    + extra_fields: `{...}`(string, required) - 设备激活信息
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应消息
        
## 在线 [POST /behavior/online]
+ Parameters
    + did: `9fbe13a77e3a2898a71d3e12fe1136fb`(string, required) - 设备ID
    + account_id: `84`(string, optional) - 账号ID
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应消息

## 离开 [POST /behavior/offline]
+ Parameters
    + did: `9fbe13a77e3a2898a71d3e12fe1136fb`(string, required) - 设备ID
    + account_id: `84`(string, optional) - 账号ID
+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应消息
