<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
## 关于
该适用SmartWork V1.0版本的android、ios客户端使用

## 语言·当前{{.language}}
文档支持中英文，可点击切换

[English](http://api.smartwork.mobi/) | [中文](http://api.smartwork.mobi/)

## 环境·当前{{.host}}
修改接口调用环境

[开发-HOST](http://api.smartwork.mobi/) | [线上-HOST](http://api.smartdo.io/)

## 公共参数
调用API时，必须传入系统级参数和对应的应用级参数。各个API的输入参数和返回结果详见API文档
<p class="text-center">
    <div class="table-responsive">
      <table class="table table-bordered">
          <tr>
              <th width="120">参数名称</th>
              <th width="120">类型</th>
              <th width="120">必须</th>
              <th>备注</th>
          </tr>
          <tr>
              <td>app_key</td>
              <td>String</td>
              <td>是</td>
              <td>应用的app_key</td>
          </tr>
          <tr>
              <td>timestamp</td>
              <td>String</td>
              <td>是</td>
              <td>当前毫秒时间戳(10位UTC秒数+3位毫秒数),如:1388890492362</td>
          </tr>
          <tr>
              <td>did</td>
              <td>String</td>
              <td>是</td>
              <td>设备唯一ID</td>
          </tr>
          <tr>
              <td>sign</td>
              <td>String</td>
              <td>是</td>
              <td>签名</td>
          </tr>
      </table>
  </div>
</p>

## 接口鉴权
1. 调用API时需要对除GET外所有请求参数进行签名（除签名和图片）
2. 签名方式为 md5(sha1(value .... + value+app_secret))，其中value对是除签名所有请求参数按key做的升序排列，value无需编码


## 接口响应

**正常**
```
    {
      “result”: , //具体业务数据，参照具体API
      “msg”: “success”
      “code”: “200”
    }
```

**异常**
```
    {
      “result”: [],
      “msg”: “invalid request arguments”,
      “code”: “400”, // 400/401/403/404/500…
    }
```
## Restful接口请求说明
+ **GET**：获取资源数据
  1. 请求可不加签权处理
  2. 支持等幂性
+ **POST**：新增资源数据
  1. 请求必须加签权处理
+ **PUT**：更新资源数据
  1. 请求必须加签权处理
  2. 支持等幂性
+ **DELETE**：删除资源数据
  1. 请求必须加签权处理
  2. 支持等幂性

## 注意事项
1. 所有的请求和响应数据编码皆为utf-8格式，为restful请求，请求数据格式(除开GET请求)为json格式
2. 含有上传图片的请求一律使用post请求，Content-Type为multipart/form-data
3. 返回结果是json格式
4. 调试模式（传参debug=true，测试环境有效）：签名异常返回签名信息
5. 接口限定5秒的安全保护机制

## 接口目录
+ [Account](#账号服务)
+ [Task](#任务管理)
+ [Search](#搜索服务)
+ [Evaluate](#评估服务)
+ [Feed](#资讯管理)
+ [Trade](#交易管理)
+ [Sync](#同步服务)
