
<!-- When server error, the response return the error message. -->
## About
This is the api document for smartwork v1.0 server. It's only for self-apps whose is android, ios application to input or output data with server.

## Language
Change language of Document.

[English](http://api.smartwork.mobi/) | [中文](http://api.smartwork.mobi/)

## Environment
Change host for dev or online Environment.

[dev-HOST](http://api.smartwork.mobi/) | [online-HOST](http://api.smartwork.mobi/)

## Api Details
+ [Account]($)
+ [Task]($)
+ [Search]($)
+ [Evaluate]($)
+ [Feed]($)
+ [Pay]($)
+ [Sync]($)
