# User模块
用户注册信息获取等。

## 登陆接口 [/v1/user/login]
用户登录

### 接口 [GET]
描述信息

+ Parameters

+ Response 200 (application/json)

    ```
    {
        "code":200,
        "message":"OK",
        "result":"Hello Smartwork"
    }
    ```

## 用户信息接口 [/v1/user/userInfo]
这里定义接口的描述信息

### 获取用户信息 [GET]
描述信息

+ Parameters
    + username: `test` (sting) - 用户名
    + password: `test` (sting) - 密码

+ Response 200 (application/json)

    ```
    {
        "code":200,
        "message":"OK",
        "result":{
            "username":"default value"
        }
    }
    ```

### 修改用户信息 [PUT]
描述信息

+ Parameters
    + username: `test` (sting) - 用户名
    + password: `test` (sting) - 密码

+ Response 200 (application/json)

    ```
    {
        "code":200,
        "message":"OK",
        "result":{
            "username":"default value"
        }
    }
    ```

### 删除用户信息 [DELETE]
描述信息

+ Parameters
    + username: `test` (sting) - 用户名
    + password: `test` (sting) - 密码

+ Response 200 (application/json)

    ```
    {
        "code":200,
        "message":"OK",
        "result":{
            "username":"default value"
        }
    }
    ```

### 新增用户信息 [POST]
描述信息

+ Parameters
    + username: `test` (sting) - 用户名
    + password: `test` (sting) - 密码

+ Response 200 (application/json)

    ```
    {
        "code":200,
        "message":"OK",
        "result":{
            "username":"default value"
        }
    }
    ```
