# Group 账号服务

# 社交账号 [/social]

## 登录社交账号 [POST /user/social]
+ Parameters
    + social_id: `optm92nakns1nknklin1m=`(string , required) - 社交账号ID
      （来着社交账号唯一的open_id）
    + social_type: `facebook`(enum[string], required) - 社交账号类型
      （国内支持微信:wechat、QQ:qq、微博:weibo，国外支持Google:google、Facebook:facebook、Twitter:twitter）
      + Members
        + `wechat`
        + `qq`
        + `weibo`
        + `facebook`
        + `google`
        + `twitter`

+ Response 200 (application/json)
    + Attributes
        + s_token:`owenxin2ns123nasdfnqj8dnqoi` (string) - 账号会话token
        + nickname:`yoyoyo` (string) - 昵称
        + avatar:`http://pic.smartdo.io/img/avatar.webp` (string) - 头像
        + role:`vip` - 账号类型
        + status: `disable` - 账户状态

# 账号 [/user]

## 获得账号信息 [GET /user]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
+ Response 200 (application/json)
    + Attributes
        + s_token:`owenxin2ns123nasdfnqj8dnqoi` (string) - 账号会话token
        + nickname:`yoyoyo` (string) - 昵称
        + avatar:`http://pic.smartdo.io/img/avatar.webp` (string) - 头像
        + role:`vip` - 账号类型
        + email:`you@example.com` - 邮箱
        + device:`{...}` - 设备信息
        + social:`{...}` - 社交账号信息

## 登录账号 [POST /user]
+ Parameters
    + email: `you@example.com`(string , required) - 账号邮件
      （将作为账号唯一的标识）
    + password: `*******`(string, required) - 账号密码
      （必须包含数字[0-9]和字母[A-Za-z]，长度大于等于8位）

+ Response 200 (application/json)
    + Attributes
        + s_token:`owenxin2ns123nasdfnqj8dnqoi` (string) - 账号会话token
        + nickname:`yoyoyo` (string) - 昵称
        + avatar:`http://pic.smartdo.io/img/avatar.webp` (string) - 头像
        + role:`vip` - 账号类型
        + status: `disable` - 账户状态

## 更新用户 [PUT /user]
+ Parameters
    + s_token: `owenxin2ns123nasdfnqj8dnqoi`(string , required) - 账号会话token
    + username: `wanger`(string, optional) - 用户名
    + email: `you@example.com`(string, optional) - 邮箱
    + password: `*******`(string, optional) - 密码
    + newpassword: `*******`(string, optional) - 新密码（修改密码时，必须填写旧密码）
    + avatar: `https://picture.smartdo.io/avatar/98381623`(string, optional) - 头像

+ Response 200 (application/json)
    + Attributes
        + message:`ok` (string) - 响应消息
